version: "3.9"
services:
  app:
    build:         
      context: ./app
      dockerfile: Dockerfile.dev
    volumes:
      - /c/Users/Owner/prodev-composed-services/app/data:/usr/src/app/data
      - /c/Users/Owner/prodev-composed-services/app/src:/usr/src/app/src
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile.dev
    depends_on:
      - mongodb
    environment:
      JWT_SECRET: JWT_SECRET
      MONGODB_URL: mongodb://mongodb/prodev-composed-auth
    volumes:
      - /c/Users/Owner/prodev-composed-services/auth/src:/usr/src/app/src
  ghi:
    build: ./ghi
    depends_on:
      - app
      - auth
    ports:
      - "8910:80"
    volumes:
      - /c/Users/Owner/prodev-composed-services/ghi/static:/usr/share/nginx/html
  mongodb:
    image: "mongo:4-bionic"
    volumes:
      - /c/Users/Owner/prodev-composed-services/auth/data:/data/db
